"""Labeling logs → recipients summary (research R7). Never copies text, chunk ids or raw bodies.

Each group is (model id, backend, hosting provider as logged). Local backends (Ollama, local
OpenAI-compatible servers) are recorded too, so the privacy notice can say what stayed on the machine.
"""

from __future__ import annotations

import datetime as dt
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

UNRECORDED = "unrecorded"


def log_key(model_id: str, backend: str, provider: str) -> str:
    return f"{model_id}|{backend}|{provider}"


def _provider(backend: str, manifest: dict[str, Any], raw: dict[str, Any]) -> str:
    meta = raw.get("backend_meta") or {}
    if backend == "openrouter":
        return meta.get("provider") or UNRECORDED
    if backend == "claude_cli":
        return "anthropic-consumer-subscription"
    if backend in ("ollama", "openai_compat"):
        return f"local:{manifest.get('host') or meta.get('host') or 'unknown'}"
    return meta.get("provider") or manifest.get("host") or UNRECORDED


def collect(run_dirs: list[Path]) -> list[dict[str, Any]]:
    groups: dict[str, dict[str, Any]] = {}
    calls: dict[str, dict[str, int]] = defaultdict(lambda: {"ok": 0, "error": 0})
    for base in run_dirs:
        for manifest_path in sorted(Path(base).glob("*/manifest.json")):
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            backend, model_id = manifest.get("backend", "?"), manifest.get("model_id", "?")
            for raw_path in sorted((manifest_path.parent / "raw").glob("*.json")):
                raw = json.loads(raw_path.read_text(encoding="utf-8"))
                key = log_key(model_id, backend, _provider(backend, manifest, raw))
                g = groups.setdefault(
                    key,
                    {
                        "model_id": model_id,
                        "backend": backend,
                        "hosting_provider": key.split("|", 2)[2],
                        "roles": set(),
                        "first_call": None,
                        "last_call": None,
                        "runs": set(),
                    },
                )
                g["roles"].add(manifest.get("role", "?"))
                g["runs"].add(manifest.get("run_id", manifest_path.parent.name))
                ts = raw.get("request_ts")
                if ts:
                    g["first_call"] = min(filter(None, [g["first_call"], ts]))
                    g["last_call"] = max(filter(None, [g["last_call"], ts]))
                calls[key]["error" if raw.get("error") else "ok"] += 1
    out = []
    for key in sorted(groups):
        g = groups[key]
        out.append(
            {
                "route_id": "",
                "model_id": g["model_id"],
                "backend": g["backend"],
                "hosting_provider": g["hosting_provider"],
                "roles": sorted(g["roles"]),
                "first_call": g["first_call"],
                "last_call": g["last_call"],
                "calls_ok": calls[key]["ok"],
                "calls_error": calls[key]["error"],
                "runs": sorted(g["runs"]),
            }
        )
    return out


def assign_routes(recipients: list[dict[str, Any]], routes: list[dict[str, Any]]) -> None:
    """Fill route_id from the routes' `log_matches`; unmatched entries get 'unregistered'."""
    index = {m: r["id"] for r in routes for m in r.get("log_matches", [])}
    for rec in recipients:
        rec["route_id"] = index.get(
            log_key(rec["model_id"], rec["backend"], rec["hosting_provider"]), "unregistered"
        )


def write(path: Path, recipients: list[dict[str, Any]], run_dirs: list[Path], root: Path) -> None:
    sources = []
    for d in run_dirs:
        p = Path(d).resolve()
        sources.append(
            p.relative_to(root.resolve()).as_posix() if p.is_relative_to(root.resolve()) else str(d)
        )
    data = {"generated_at": dt.date.today().isoformat(), "sources": sources, "recipients": recipients}
    path.write_text(
        "# Generated by `zoo compliance recipients`; do not edit by hand.\n"
        + yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
