"""Emit C sources (model_zoo.h / model_zoo.c) for microinfer from QModels."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from .model import OPS, QModel

HEADER = "/* AUTO-GENERATED by mobility_model_zoo.edge.int8.codegen - do not edit. */\n"


def _ident(name: str) -> str:
    """C identifier for a model name: `picket-mlp` -> `picket_mlp`, `3axis` -> `m_3axis`."""
    ident = "".join(c if c.isascii() and c.isalnum() else "_" for c in name)
    return f"m_{ident}" if not ident or ident[0].isdigit() else ident


def _array(ctype: str, name: str, values: np.ndarray, per_line: int = 24) -> str:
    vals = [str(int(v)) for v in np.asarray(values).reshape(-1)]
    if ctype == "int32_t":
        # INT32_MIN cannot be written as a plain literal.
        vals = ["(-2147483647 - 1)" if v == "-2147483648" else v for v in vals]
    lines = [", ".join(vals[i : i + per_line]) for i in range(0, len(vals), per_line)]
    body = ",\n    ".join(lines) if lines else "0"
    size = max(len(vals), 1)
    return f"static const {ctype} {name}[{size}] MI_CONST = {{\n    {body}\n}};\n"


def model_to_c(model: QModel) -> str:
    m = _ident(model.name)
    out = [f"/* {model.name}: {model.description} */\n"]
    layer_rows = []
    for i, lyr in enumerate(model.layers):
        p = f"{m}_l{i}"
        if lyr.has_params:
            out.append(_array("int8_t", f"{p}_w", lyr.weights.astype(np.int8)))
            if lyr.bias is not None:
                out.append(_array("int32_t", f"{p}_b", lyr.bias.astype(np.int32)))
            out.append(_array("int32_t", f"{p}_m", lyr.mult.astype(np.int32)))
            out.append(_array("int8_t", f"{p}_s", lyr.shift.astype(np.int8)))
            refs = (f"{p}_w", f"{p}_b" if lyr.bias is not None else "NULL", f"{p}_m", f"{p}_s")
            n_mult = int(lyr.mult.size)
        else:
            refs = ("NULL", "NULL", "NULL", "NULL")
            n_mult = 0
        if lyr.op == "dense":
            in_hwc = (1, 1, int(np.prod(lyr.in_shape)))
            out_hwc = (1, 1, int(np.prod(lyr.out_shape)))
        else:
            in_hwc, out_hwc = lyr.in_shape, lyr.out_shape
        layer_rows.append(
            "    {{ {op}, {kh}, {kw}, {sh}, {sw}, {pt}, {pl}, {fl}, {ih}, {iw}, {ic}, {oh}, {ow}, {oc}, "
            "{izp}, {ozp}, {amin}, {amax}, {nm}, {w}, {b}, {mu}, {sh_} }}".format(
                op=f"MI_OP_{lyr.op.upper()}",
                kh=lyr.kernel[0],
                kw=lyr.kernel[1],
                sh=lyr.stride[0],
                sw=lyr.stride[1],
                pt=lyr.pad[0],
                pl=lyr.pad[1],
                fl="MI_FLAG_SINGLE_ROUNDING" if lyr.rounding == "single" else 0,
                ih=in_hwc[0],
                iw=in_hwc[1],
                ic=in_hwc[2],
                oh=out_hwc[0],
                ow=out_hwc[1],
                oc=out_hwc[2],
                izp=lyr.in_zp,
                ozp=lyr.out_zp,
                amin=lyr.act_min,
                amax=lyr.act_max,
                nm=n_mult,
                w=refs[0],
                b=refs[1],
                mu=refs[2],
                sh_=refs[3],
            )
        )
    out.append(
        f"static const mi_layer_t {m}_layers[{len(model.layers)}] = {{\n"
        + ",\n".join(layer_rows)
        + "\n};\n"
    )
    n_tests = int(model.test_inputs.shape[0])
    out.append(_array("int8_t", f"{m}_test_in", model.test_inputs.astype(np.int8)))
    out.append(_array("int8_t", f"{m}_test_out", model.test_outputs.astype(np.int8)))
    desc = model.description.replace("\\", "\\\\").replace('"', '\\"')
    out.append(
        f"const mi_model_t mi_model_{m} = {{\n"
        f'    "{model.name}", "{desc}", {len(model.layers)}, {m}_layers,\n'
        f"    {model.in_size}u, {model.out_size}u, {model.arena_size()}u, {model.param_bytes()}u,\n"
        f"    {model.macs()}u, 0x{model.crc32():08x}u, {n_tests}, {m}_test_in, {m}_test_out\n}};\n"
    )
    return "".join(out)


def _max_chain(macro: str, values: list) -> str:
    """Preprocessor running maximum that skips models excluded via MI_EXCLUDE_*."""
    out = [f"#define {macro}_0 4u\n"]
    for i, (m, v) in enumerate(values):
        guard = f"MI_EXCLUDE_{_ident(m.name).upper()}"
        out.append(
            f"#if !defined({guard}) && {v}u > {macro}_{i}\n#define {macro}_{i + 1} {v}u\n"
            f"#else\n#define {macro}_{i + 1} {macro}_{i}\n#endif\n"
        )
    out.append(f"#define {macro} {macro}_{len(values)}\n\n")
    return "".join(out)


def zoo_sources(models: list[QModel]) -> tuple[str, str]:
    for model in models:
        for lyr in model.layers:
            if lyr.op not in OPS:
                raise ValueError(f"{model.name}: unsupported op {lyr.op}")
    h = [
        HEADER,
        '#ifndef MODEL_ZOO_H\n#define MODEL_ZOO_H\n\n#include "microinfer.h"\n\n',
        '#ifdef __cplusplus\nextern "C" {\n#endif\n\n',
        "/* Buffer sizes = maximum over the models that are compiled in. */\n",
        _max_chain("MI_ZOO_ARENA_SIZE", [(m, m.arena_size()) for m in models]),
        _max_chain("MI_ZOO_MAX_IN", [(m, m.in_size) for m in models]),
        _max_chain("MI_ZOO_MAX_OUT", [(m, m.out_size) for m in models]),
    ]
    for m in models:
        h.append(f"extern const mi_model_t mi_model_{_ident(m.name)};\n")
    h.append("\n/* NULL-terminated; models can be dropped with -DMI_EXCLUDE_<NAME>. */\n")
    h.append("extern const mi_model_t *const mi_zoo[];\nextern const unsigned mi_zoo_count;\n\n")
    h.append("#ifdef __cplusplus\n}\n#endif\n\n#endif /* MODEL_ZOO_H */\n")

    c = [HEADER, '#include "model_zoo.h"\n\n#include <stddef.h>\n\n']
    for m in models:
        guard = f"MI_EXCLUDE_{_ident(m.name).upper()}"
        c.append(f"#ifndef {guard}\n{model_to_c(m)}#endif /* {guard} */\n\n")
    c.append("const mi_model_t *const mi_zoo[] = {\n")
    for m in models:
        guard = f"MI_EXCLUDE_{_ident(m.name).upper()}"
        c.append(f"#ifndef {guard}\n    &mi_model_{_ident(m.name)},\n#endif\n")
    c.append("    NULL\n};\n\nconst unsigned mi_zoo_count = sizeof(mi_zoo) / sizeof(mi_zoo[0]) - 1u;\n")
    return "".join(h), "".join(c)


def write_zoo_sources(models: list[QModel], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    h, c = zoo_sources(models)
    (out_dir / "model_zoo.h").write_text(h)
    (out_dir / "model_zoo.c").write_text(c)
