"""`zoo/MODELS.md`: the generated overview of the zoo (spec FR-004). Sandbox models are left out."""

from __future__ import annotations

from mobility_model_zoo.release.registry import Registry, parse_version

HEADER = (
    "# Models in the mobility model zoo\n\nGenerated by `zoo index` from `zoo/`. Do not edit by hand.\n"
    "Website: https://mhabedank.github.io/mobility-model-zoo/\n"
)


def render(reg: Registry) -> str:
    parts = [HEADER]
    for topic in reg.topics():
        if topic["id"] == "sandbox":
            continue
        rows = []
        for name in reg.model_names():
            model = reg.model_raw(name)
            if model.get("topic") != topic["id"]:
                continue
            published = reg.published_versions(name)
            if published:
                latest = max(published, key=parse_version)
                status = reg.record_raw(name, latest)["status"]
            else:
                latest, status = "–", "not published"
            link = f"[{model['repos']['public']}](https://huggingface.co/{model['repos']['public']})"
            rows.append(f"| `{name}` | {model['task']} | {latest} | {status} | {link} |")
        parts.append(f"## {topic['title']} (`{topic['id']}`)\n\n{topic['description']}\n")
        if rows:
            parts.append("| Model | Task | Latest version | Status | Hugging Face |")
            parts.append("|-------|------|----------------|--------|--------------|")
            parts.extend(rows)
        else:
            parts.append("No models yet.")
        parts.append("")
    return "\n".join(parts).rstrip("\n") + "\n"


def write(reg: Registry) -> None:
    (reg.zoo / "MODELS.md").write_text(render(reg), encoding="utf-8")
