"""Release operations: init-model, stage, build, preview, publish, deprecate (contracts/cli.md).

All Hub access goes through a `Hub` (or a test `FakeHub`). Nothing here deletes or moves a tag or
changes the visibility of an existing repository.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import tempfile
from collections.abc import Callable
from pathlib import Path, PurePosixPath
from typing import Any

from mobility_model_zoo.release import card as cards
from mobility_model_zoo.release import index
from mobility_model_zoo.release.errors import (
    ApprovalRefused,
    GateFailed,
    ImmutabilityRefused,
    UsageError,
)
from mobility_model_zoo.release.gate import IGNORED_STAGING_FILES, Gate, GitRepo
from mobility_model_zoo.release.hub import sha256_file
from mobility_model_zoo.release.registry import ORG, Registry, parse_version, schema_errors

Say = Callable[[str], None]
PUBLISH_RULES = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 15}


def _today() -> str:
    return dt.date.today().isoformat()


def _now() -> str:
    return dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def preview_branch(version: str) -> str:
    return f"rc-v{version}"


# ---- init-model --------------------------------------------------------------------------------
def init_model(reg: Registry, name: str, hub: Any, say: Say) -> str:
    model = reg.model(name)
    repo = model["repos"]["staging"]
    visibility = hub.visibility(repo)
    if visibility == "public":
        raise GateFailed([f"{repo} exists and is public; staging repos must be private"])
    if visibility is None:
        hub.create_repo(repo, private=True)
        say(f"created private staging repo {repo}")
    else:
        say(f"staging repo {repo} already exists (private)")
    say(f"add {repo} to the repo list of HF_STAGING_TOKEN (write access) on the Hub")
    return repo


# ---- stage -------------------------------------------------------------------------------------
def forbidden_upload(path: str) -> str | None:
    p = PurePosixPath(path)
    if p.is_absolute() or ".." in p.parts:
        return "not a relative path"
    if p.parts[0] == "data" or p.name == ".env" or p.suffix == ".jsonl":
        return "data, secrets or labeling output may not be uploaded"
    if p.name.endswith(".eval.npz"):
        return "evaluation sets hold dataset content and may not be uploaded"
    if path in {"README.md", "build.json"}:
        return "generated by the pipeline"
    return None


def _record_template(reg: Registry, name: str, version: str, model: dict[str, Any]) -> dict[str, Any]:
    major = parse_version(version)[0]
    return {
        "model": name,
        "version": version,
        "date": _today(),
        "status": "experimental" if major == 0 else "released",
        "change_type": "initial" if not reg.published_versions(name) else "minor",
        "changes": "",
        "output_format_version": "",
        "sandbox": model["topic"] == "sandbox",
        "files": [],
        "staging": {"repo": model["repos"]["staging"], "revision": ""},
        "recipe": {"git_commit": "", "config": "", "doc": ""},
        "provenance": {"sources": [], "teachers": [], "spike_data": False},
        "evaluation": {"benchmark": "", "reference": "", "results": f"results/{version}/quality.json"},
        "performance": {
            "hardware": "",
            "budget": (
                {"ram_kb": 0, "flash_kb": 0, "target": ""}
                if Registry.runtime(model) == "mcu"
                else {"ram_gb": 0, "gpu": False}
            ),
            "results": f"results/{version}/performance.json",
        },
        "published": None,
        "deprecated": None,
    }


def stage(reg: Registry, name: str, version: str, src: Path, hub: Any, say: Say) -> str:
    parse_version(version)
    model = reg.model(name)
    repo = model["repos"]["staging"]
    path = reg.record_path(name, version)
    record = (
        reg.record_raw(name, version) if path.exists() else _record_template(reg, name, version, model)
    )
    if record.get("published"):
        raise ImmutabilityRefused(f"{name} {version} is already published")
    visibility = hub.visibility(repo)
    if visibility is None:
        raise UsageError(f"{repo} does not exist: run `zoo init-model {name}` first")
    if visibility != "private":
        raise GateFailed([f"{repo} is public; staging repos must be private"])
    if not src.is_dir():
        raise UsageError(f"{src} is not a directory")
    files = {p.relative_to(src).as_posix(): p for p in sorted(src.rglob("*")) if p.is_file()}
    problems = [f"{p}: {why}" for p in files if (why := forbidden_upload(p))]
    if problems:
        raise GateFailed(problems)
    if not files:
        raise UsageError(f"{src} contains no files")
    revision = hub.commit(repo, files, f"Stage {name} {version}")
    record["files"] = [
        {"path": p, "sha256": sha256_file(f), "size_bytes": f.stat().st_size} for p, f in files.items()
    ]
    record["staging"] = {"repo": repo, "revision": revision}
    reg.write_record(name, version, record)
    say(f"staged {len(files)} files to {repo}@{revision}; record {path.relative_to(reg.root)} updated")
    return revision


# ---- check and build ---------------------------------------------------------------------------
def check(reg: Registry, name: str, version: str, hub: Any, runner: Any, say: Say) -> Gate:
    gate = Gate(reg, name, version, hub=hub, runner=runner)
    gate.run(say)
    return gate


def build(reg: Registry, name: str, version: str, out: Path, hub: Any, runner: Any, say: Say) -> dict:
    gate = check(reg, name, version, hub, runner, say)
    record = gate.record
    out.mkdir(parents=True, exist_ok=True)
    files = []
    for f in record["files"]:
        local = hub.download(record["staging"]["repo"], f["path"], record["staging"]["revision"], out)
        if sha256_file(local) != f["sha256"]:
            raise GateFailed([f"rule 5: downloaded {f['path']} does not match its sha256"])
        files.append({"path": f["path"], "sha256": f["sha256"], "size_bytes": f["size_bytes"]})
    card = gate.card or ""
    (out / "README.md").write_text(card, encoding="utf-8")
    info = {
        "model": name,
        "version": version,
        "card_sha256": hashlib.sha256(card.encode("utf-8")).hexdigest(),
        "files": files,
        "tag_commit": gate.git.head(),
        "staging_revision": record["staging"]["revision"],
    }
    (out / "build.json").write_text(json.dumps(info, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    say(f"built {name} {version} in {out} (card sha256 {info['card_sha256']})")
    return info


def preview(reg: Registry, name: str, version: str, build_dir: Path, hub: Any, say: Say) -> str:
    record = reg.record(name, version)
    info = json.loads((build_dir / "build.json").read_text(encoding="utf-8"))
    if info["model"] != name or info["version"] != version:
        raise UsageError(f"{build_dir} holds a build of {info['model']} {info['version']}")
    repo, branch = record["staging"]["repo"], preview_branch(version)
    hub.replace_branch(repo, branch, record["staging"]["revision"])
    hub.commit(
        repo,
        {"README.md": build_dir / "README.md", "build.json": build_dir / "build.json"},
        f"Preview {name} v{version}",
        branch=branch,
    )
    url = f"https://huggingface.co/{repo}/blob/{branch}/README.md"
    say(f"preview: {url}")
    say(f"card sha256: {info['card_sha256']}")
    return url


# ---- publish -----------------------------------------------------------------------------------
def _same_files(hub: Any, repo: str, revision: str, expected: dict[str, Path]) -> bool:
    present = set(hub.list_files(repo, revision)) - IGNORED_STAGING_FILES
    if present != set(expected):
        return False
    return all(
        hub.file_info(repo, path, revision) == (sha256_file(f), f.stat().st_size)
        for path, f in expected.items()
    )


def publish(
    reg: Registry, name: str, version: str, confirm: str, hub: Any, say: Say, git: GitRepo | None = None
) -> str:
    if confirm != f"{name}/v{version}":
        raise ApprovalRefused(f"--confirm must be {name}/v{version}")
    git = git or GitRepo(reg.root)
    model = reg.model(name)
    record = reg.record(name, version)
    staging, branch = record["staging"]["repo"], preview_branch(version)
    if hub.visibility(staging) is None or branch not in hub.refs(staging)["branches"]:
        raise ApprovalRefused(f"no reviewed preview {staging}@{branch}: run release-verify first")

    with tempfile.TemporaryDirectory(prefix="zoo-publish-") as tmp:
        work = Path(tmp)
        readme = hub.download(staging, "README.md", branch, work)
        info = json.loads(hub.download(staging, "build.json", branch, work).read_text(encoding="utf-8"))
        if info.get("tag_commit") != git.head():
            raise ApprovalRefused("the preview was not built from the tag commit being published")
        if sha256_file(readme) != info.get("card_sha256"):
            raise ApprovalRefused("the preview card does not match build.json")
        upload = {"README.md": readme}
        for f in record["files"]:
            local = hub.download(staging, f["path"], branch, work)
            if sha256_file(local) != f["sha256"]:
                raise ApprovalRefused(f"preview file {f['path']} does not match the release record")
            upload[f["path"]] = local

        card = readme.read_text(encoding="utf-8")
        public = model["repos"]["public"]
        sandbox = model["topic"] == "sandbox"
        tag = f"v{version}"
        # An earlier run that failed after tagging (for example while adding the collection) is
        # resumed: the tag must point at main and main must hold exactly this version's files.
        # Any other existing tag still fails rule 4.
        resumed = False
        if not record.get("published") and hub.visibility(public) is not None:
            refs = hub.refs(public)
            head = refs["branches"].get("main")
            resumed = bool(head and refs["tags"].get(tag) == head
                           and _same_files(hub, public, head, upload))
        rules = PUBLISH_RULES - {4} if resumed else PUBLISH_RULES
        Gate(reg, name, version, hub=hub, card=card, only=rules, git=git).run(say)

        if hub.visibility(public) is None:
            hub.create_repo(public, private=sandbox)
            say(f"created {'private' if sandbox else 'public'} repo {public}")
        head = hub.refs(public)["branches"].get("main")
        if resumed:
            commit = head
            say(f"{public} {tag} already points at this version (interrupted run); finishing")
        else:
            if head and _same_files(hub, public, head, upload):
                commit = head
                say(f"{public}@main already holds this version (earlier run); only tagging")
            else:
                commit = hub.commit(public, upload, f"Release {name} v{version}")
            hub.create_tag(public, tag, commit)
        say(f"published {public} {tag} at {commit}")

    if not sandbox:
        add_to_collection(reg, model, hub, say)
    record["published"] = {
        "repo_commit": commit,
        "tag": f"v{version}",
        "published_at": _now(),
        "card_sha256": info["card_sha256"],
    }
    errors = schema_errors("release-record", record)
    if errors:
        raise GateFailed(errors)
    reg.write_record(name, version, record)
    index.write(reg)
    return commit


def add_to_collection(reg: Registry, model: dict[str, Any], hub: Any, say: Say) -> None:
    topics = reg.topics()
    topic = next(t for t in topics if t["id"] == model["topic"])
    if not topic.get("hf_collection"):
        topic["hf_collection"] = hub.create_collection(ORG, topic["title"], topic["description"])
        reg.write_topics(topics)
        say(f"created collection {topic['hf_collection']}")
    hub.add_collection_item(topic["hf_collection"], model["repos"]["public"], model["summary"])


# ---- deprecate ---------------------------------------------------------------------------------
def deprecate(
    reg: Registry, name: str, version: str, reason: str, successor: str | None, hub: Any, say: Say
) -> str:
    model = reg.model(name)
    record = reg.record(name, version)
    if not record.get("published"):
        raise UsageError(f"{name} {version} is not published")
    if successor is not None:
        parse_version(successor)
    record["status"] = "deprecated"
    record["deprecated"] = {"reason": reason, "successor": successor}
    reg.write_record(name, version, record)

    published = reg.published_versions(name)
    latest = max(published, key=parse_version)
    card = cards.render(
        cards.CardInput(
            reg,
            name,
            latest,
            deprecated_banner=True,
            model=cards.model_at_tag(reg, name, latest),
            example_outputs=_examples_from_hub(hub, model["repos"]["public"], latest),
        )
    )
    with tempfile.TemporaryDirectory(prefix="zoo-deprecate-") as tmp:
        path = Path(tmp) / "README.md"
        path.write_text(card, encoding="utf-8")
        commit = hub.commit(
            model["repos"]["public"], {"README.md": path}, f"Deprecate {name} v{version}"
        )
    what = "banner" if latest == version else "version history row"
    say(f"deprecated {name} {version} ({what} updated in {model['repos']['public']}@{commit})")
    index.write(reg)
    return commit


def _examples_from_hub(hub: Any, repo: str, version: str) -> dict[str, str]:
    """Example outputs from the published card, so a card-only update keeps them."""
    with tempfile.TemporaryDirectory() as tmp:
        text = hub.download(repo, "README.md", "main", Path(tmp)).read_text(encoding="utf-8")
    outputs, name = {}, None
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("### Example ") and "`" in line:
            name = line.split("`")[1]
        if name and line == "Output:":
            j = i + 2  # skip the blank line and the opening fence
            block = []
            while j + 1 < len(lines) and not lines[j + 1].startswith("```"):
                j += 1
                block.append(lines[j])
            outputs[name] = "\n".join(block)
            name = None
    return outputs
